// Structure des catégories de loisirs avec leurs sous-catégories et attributs
final Map<String, Map<String, dynamic>> categoryStructure = {
  'Sports & Activités Physiques': {
    'sous-catégories': [
      'Sports d\'équipe',
      'Sports individuels',
      'Activités de plein air',
      'Sports nautiques',
      'Fitness & Bien-être',
      'Sports extrêmes',
      'Sports d\'hiver',
    ],
    'aspects': [
      'Qualité des installations',
      'Encadrement professionnel',
      'Variété des activités',
      'Rapport qualité-prix',
    ],
    'emotions': [
      'Dynamisme',
      'Challenge',
      'Adrénaline',
      'Dépassement de soi',
      'Esprit d\'équipe',
      'Détente',
    ],
  },
  'Art & Culture': {
    'sous-catégories': [
      'Musées',
      'Galeries d\'art',
      'Théâtres',
      'Cinémas',
      'Salles de concert',
      'Écoles artistiques',
      'Ateliers créatifs',
    ],
    'aspects': [
      'Qualité de la programmation',
      'Accueil du public',
      'Accessibilité',
      'Innovations artistiques',
    ],
    'emotions': [
      'Émerveillement',
      'Inspiration',
      'Réflexion',
      'Enrichissement culturel',
      'Émotion',
      'Découverte',
    ],
  },
  'Vie Nocturne': {
    'sous-catégories': [
      'Bars',
      'Clubs & Discothèques',
      'Bars à cocktails',
      'Cabarets',
      'Concerts live',
      'Soirées thématiques',
    ],
    'aspects': [
      'Ambiance',
      'Qualité du son',
      'Offre de boissons',
      'Service',
      'Sécurité',
    ],
    'emotions': [
      'Convivialité',
      'Euphorie',
      'Évasion',
      'Sociabilité',
      'Festif',
    ],
  },
  'Bien-être & Relaxation': {
    'sous-catégories': [
      'Spas',
      'Centres de massage',
      'Hammams',
      'Saunas',
      'Centres de yoga',
      'Méditation',
      'Thermes',
    ],
    'aspects': [
      'Qualité des soins',
      'Professionnalisme',
      'Cadre & Ambiance',
      'Propreté',
      'Variété des prestations',
    ],
    'emotions': [
      'Détente',
      'Ressourcement',
      'Harmonie',
      'Apaisement',
      'Bien-être',
    ],
  },
  'Éducation & Découverte': {
    'sous-catégories': [
      'Ateliers pédagogiques',
      'Conférences',
      'Cours & Formations',
      'Visites guidées',
      'Dégustations',
      'Découvertes nature',
    ],
    'aspects': [
      'Qualité pédagogique',
      'Intérêt du contenu',
      'Interactivité',
      'Adaptation au public',
    ],
    'emotions': [
      'Curiosité',
      'Étonnement',
      'Compréhension',
      'Apprentissage',
      'Satisfaction intellectuelle',
    ],
  },
  'Événements Spéciaux': {
    'sous-catégories': [
      'Festivals',
      'Foires & Salons',
      'Conventions',
      'Événements sportifs',
      'Célébrations culturelles',
      'Événements saisonniers',
    ],
    'aspects': [
      'Organisation',
      'Programmation',
      'Infrastructures',
      'Animations',
      'Services aux visiteurs',
    ],
    'emotions': [
      'Excitation',
      'Émerveillement',
      'Sentiment d\'appartenance',
      'Fête',
      'Découverte',
    ],
  },
  'Aventure & Plein Air': {
    'sous-catégories': [
      'Randonnées',
      'Parcs d\'aventure',
      'Sports extrêmes',
      'Expéditions',
      'Activités nautiques',
      'Observation de la nature',
    ],
    'aspects': [
      'Sécurité',
      'Encadrement',
      'Niveau de difficulté',
      'Cadre naturel',
      'Matériel fourni',
    ],
    'emotions': [
      'Liberté',
      'Adrénaline',
      'Connexion à la nature',
      'Dépassement de soi',
      'Émerveillement',
    ],
  },
}; 