// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configuration par défaut pour Firebase correspondant au projet réel.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions n\'a pas été configuré pour windows - '
          'vous pouvez reconfigurer en exécutant flutterfire configure',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions n\'a pas été configuré pour linux - '
          'vous pouvez reconfigurer en exécutant flutterfire configure',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions n\'est pas supporté pour cette plateforme.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRvEPM8JZ1Wpn_J6ku4c3r5LQIocFmzOE',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'choice-app-prod',
    authDomain: 'choice-app-prod.firebaseapp.com',
    storageBucket: 'choice-app-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvEPM8JZ1Wpn_J6ku4c3r5LQIocFmzOE',
    appId: '1:123456789012:android:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'choice-app-prod',
    storageBucket: 'choice-app-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRvEPM8JZ1Wpn_J6ku4c3r5LQIocFmzOE',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'choice-app-prod',
    storageBucket: 'choice-app-prod.appspot.com',
    iosClientId: 'com.googleusercontent.apps.123456789012-abcdefghijklmnopqrstuvwxyz123456',
    iosBundleId: 'fr.choiceapp.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRvEPM8JZ1Wpn_J6ku4c3r5LQIocFmzOE',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'choice-app-prod',
    storageBucket: 'choice-app-prod.appspot.com',
    iosClientId: 'com.googleusercontent.apps.123456789012-abcdefghijklmnopqrstuvwxyz123456',
    iosBundleId: 'fr.choiceapp.app',
  );
} 