# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
